name: coodesh_challenge
description: Flutter Challenge by Coodesh

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get:
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.10
  firebase_core:
  intl:
  cached_network_image:
  image_downloader: ^0.31.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  test:



flutter:


  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
